// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbfkcsaarlupwiusinit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZmtjc2Fhcmx1cHdpdXNpbml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTg5MjQsImV4cCI6MjA2MDk5NDkyNH0.PwvzNFXAxJ29tJvPeczef-rc2ABotH7GvQXCsAHBDjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);