
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbfkcsaarlupwiusinit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZmtjc2Fhcmx1cHdpdXNpbml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTg5MjQsImV4cCI6MjA2MDk5NDkyNH0.PwvzNFXAxJ29tJvPeczef-rc2ABotH7GvQXCsAHBDjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom type that extends the generated Database type
export type CustomDatabase = Database & {
  public: {
    Tables: {
      agent_profiles: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          email: string;
          phone_number: string;
          company_name: string;
          experience: number;
          specialization: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          email: string;
          phone_number: string;
          company_name: string;
          experience: number;
          specialization: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          email?: string;
          phone_number?: string;
          company_name?: string;
          experience?: number;
          specialization?: string;
          created_at?: string;
          updated_at?: string;
        };
      },
      individual_profiles: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          phone_number: string;
          email: string;
          address: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name: string;
          phone_number: string;
          email: string;
          address?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string;
          phone_number?: string;
          email?: string;
          address?: string;
          created_at?: string;
          updated_at?: string;
        };
      }
    }
  }
}

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
